#ifndef MODELCONTROL_GLOBAL_H
#define MODELCONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODELCONTROL_LIBRARY)
#  define MODELCONTROLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODELCONTROLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODELCONTROL_GLOBAL_H
