#ifndef METAHUBCOMPUTECL_GLOBAL_H
#define METAHUBCOMPUTECL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(METAHUBCOMPUTECL_LIBRARY)
#  define METAHUBCOMPUTECL_EXPORT Q_DECL_EXPORT
#else
#  define METAHUBCOMPUTECL_EXPORT Q_DECL_IMPORT
#endif

#endif // METAHUBCOMPUTECL_GLOBAL_H
