#ifndef REPORTDOCUMENT_GLOBAL_H
#define REPORTDOCUMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REPORTDOCUMENT_LIBRARY)
#  define REPORTDOCUMENT_EXPORT Q_DECL_EXPORT
#else
#  define REPORTDOCUMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // REPORTDOCUMENT_GLOBAL_H
